apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik-system
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: web
  - port: 443
    targetPort: 443
    name: websecure
  - port: 9000
    targetPort: 9000
    name: dashboard
  selector:
    app: traefik
