# File: infrastructure/controllers/traefik.yaml
# ARM64-optimized Traefik with MetalLB LoadBalancer
apiVersion: v1
kind: Namespace
metadata:
  name: traefik-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "24.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: metallb
      namespace: metallb-system
  values:
    # ARM64 specific configurations for Raspberry Pi 4
    image:
      name: traefik
      tag: "v3.0"
      pullPolicy: IfNotPresent
    
    deployment:
      enabled: true
      replicas: 1
      # Resource limits for Pi 4
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 300m
          memory: 150Mi
    
    # Use LoadBalancer with MetalLB!
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.universe.tf/loadBalancer-class: metallb
      spec:
        externalTrafficPolicy: Local
        # Optional: request specific IP from pool
        # loadBalancerIP: "192.168.1.200"
    
    ports:
      web:
        port: 8000
        expose: true
        exposedPort: 80
        # Remove nodePort since we're using LoadBalancer
      websecure:
        port: 8443
        expose: true
        exposedPort: 443
        tls:
          enabled: true
      traefik:
        port: 9000
        expose: true
        exposedPort: 9000
    
    ingressRoute:
      dashboard:
        enabled: true
    
    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik
      kubernetesIngress:
        enabled: true
        ingressClass: traefik
        publishedService:
          enabled: true  # Now we can enable this with LoadBalancer
    
    globalArguments:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--log.level=INFO"
    
    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true"
      - "--entryPoints.web.address=:8000"
      - "--entryPoints.websecure.address=:8443"
      - "--entryPoints.traefik.address=:9000"
    
    # Pi-specific node affinity
    nodeSelector:
      kubernetes.io/arch: arm64
